/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BlogFeedDotxmlRouteImport } from './routes/blog/feed[.]xml'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'
import { Route as BlogCategoriesIndexRouteImport } from './routes/blog/categories/index'
import { Route as BlogCategoriesSlugRouteImport } from './routes/blog/categories/$slug'
import { Route as BlogPostsIndexRouteImport } from './routes/blog/posts/index'
import { Route as BlogTagsIndexRouteImport } from './routes/blog/tags/index'
import { Route as BlogTagsSlugRouteImport } from './routes/blog/tags/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogFeedDotxmlRoute = BlogFeedDotxmlRouteImport.update({
  id: '/blog/feed.xml',
  path: '/blog/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoriesIndexRoute = BlogCategoriesIndexRouteImport.update({
  id: '/blog/categories/',
  path: '/blog/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoriesSlugRoute = BlogCategoriesSlugRouteImport.update({
  id: '/blog/categories/$slug',
  path: '/blog/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostsIndexRoute = BlogPostsIndexRouteImport.update({
  id: '/blog/posts/',
  path: '/blog/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagsIndexRoute = BlogTagsIndexRouteImport.update({
  id: '/blog/tags/',
  path: '/blog/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagsSlugRoute = BlogTagsSlugRouteImport.update({
  id: '/blog/tags/$slug',
  path: '/blog/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/blog/categories/$slug': typeof BlogCategoriesSlugRoute
  '/blog/tags/$slug': typeof BlogTagsSlugRoute
  '/blog/categories/': typeof BlogCategoriesIndexRoute
  '/blog/posts/': typeof BlogPostsIndexRoute
  '/blog/tags/': typeof BlogTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/work': typeof WorkIndexRoute
  '/blog/categories/$slug': typeof BlogCategoriesSlugRoute
  '/blog/tags/$slug': typeof BlogTagsSlugRoute
  '/blog/categories': typeof BlogCategoriesIndexRoute
  '/blog/posts': typeof BlogPostsIndexRoute
  '/blog/tags': typeof BlogTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/feed.xml': typeof BlogFeedDotxmlRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/blog/categories/$slug': typeof BlogCategoriesSlugRoute
  '/blog/tags/$slug': typeof BlogTagsSlugRoute
  '/blog/categories/': typeof BlogCategoriesIndexRoute
  '/blog/posts/': typeof BlogPostsIndexRoute
  '/blog/tags/': typeof BlogTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/blog/$slug'
    | '/blog/feed.xml'
    | '/services/$slug'
    | '/work/$slug'
    | '/blog/'
    | '/services/'
    | '/work/'
    | '/blog/categories/$slug'
    | '/blog/tags/$slug'
    | '/blog/categories/'
    | '/blog/posts/'
    | '/blog/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/blog/$slug'
    | '/blog/feed.xml'
    | '/services/$slug'
    | '/work/$slug'
    | '/blog'
    | '/services'
    | '/work'
    | '/blog/categories/$slug'
    | '/blog/tags/$slug'
    | '/blog/categories'
    | '/blog/posts'
    | '/blog/tags'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/blog/$slug'
    | '/blog/feed.xml'
    | '/services/$slug'
    | '/work/$slug'
    | '/blog/'
    | '/services/'
    | '/work/'
    | '/blog/categories/$slug'
    | '/blog/tags/$slug'
    | '/blog/categories/'
    | '/blog/posts/'
    | '/blog/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogFeedDotxmlRoute: typeof BlogFeedDotxmlRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
  BlogCategoriesSlugRoute: typeof BlogCategoriesSlugRoute
  BlogTagsSlugRoute: typeof BlogTagsSlugRoute
  BlogCategoriesIndexRoute: typeof BlogCategoriesIndexRoute
  BlogPostsIndexRoute: typeof BlogPostsIndexRoute
  BlogTagsIndexRoute: typeof BlogTagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/feed.xml': {
      id: '/blog/feed.xml'
      path: '/blog/feed.xml'
      fullPath: '/blog/feed.xml'
      preLoaderRoute: typeof BlogFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/categories/': {
      id: '/blog/categories/'
      path: '/blog/categories'
      fullPath: '/blog/categories/'
      preLoaderRoute: typeof BlogCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/categories/$slug': {
      id: '/blog/categories/$slug'
      path: '/blog/categories/$slug'
      fullPath: '/blog/categories/$slug'
      preLoaderRoute: typeof BlogCategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/posts/': {
      id: '/blog/posts/'
      path: '/blog/posts'
      fullPath: '/blog/posts/'
      preLoaderRoute: typeof BlogPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tags/': {
      id: '/blog/tags/'
      path: '/blog/tags'
      fullPath: '/blog/tags/'
      preLoaderRoute: typeof BlogTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tags/$slug': {
      id: '/blog/tags/$slug'
      path: '/blog/tags/$slug'
      fullPath: '/blog/tags/$slug'
      preLoaderRoute: typeof BlogTagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogFeedDotxmlRoute: BlogFeedDotxmlRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
  BlogCategoriesSlugRoute: BlogCategoriesSlugRoute,
  BlogTagsSlugRoute: BlogTagsSlugRoute,
  BlogCategoriesIndexRoute: BlogCategoriesIndexRoute,
  BlogPostsIndexRoute: BlogPostsIndexRoute,
  BlogTagsIndexRoute: BlogTagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
